// Short recall prompts, checked against the matching Learn & Review notes.
// Each asks for one term; the answer is never included in the prompt.
const clearRecallPrompts = {
  'Byte': 'What do we call a group of 8 bits?',
  'RAM': 'Which type of memory loses its data when the power is off?',
  'Firmware': 'What software gives a device low-level instructions to control its hardware?',
  'Compiler': 'What translates source code into a target form before that result runs?',
  'Interpreter': 'What runs program instructions through a runtime?',
  'System software': 'What type of software manages the computer and supports other programs?',
  'Binary to decimal': 'What is 1010 in binary when written in decimal?',
  'Hexadecimal': 'What base-16 digit represents decimal 15?',
  'Virtualization': 'What lets one physical computer run several virtual computers?',
  'SaaS': 'Which cloud model gives users a complete application over the internet?',
  'ROM': 'What non-volatile memory keeps its contents without power?',
  'PaaS': 'Which cloud model gives developers a managed platform to build and deploy apps?',
  "Two's complement": 'What binary method is commonly used to represent negative integers?',
  'AND': 'Which logic operator is true only when both inputs are true?',
  'OR': 'Which logic operator is true when at least one input is true?',
  'XOR': 'Which logic operator is true when exactly one input is true?',
  'Material implication': 'For P → Q, when is the statement false?',
  'Converse': 'What do you call Q → P when the original statement is P → Q?',
  'Inverse': 'What do you call ¬P → ¬Q when the original is P → Q?',
  'Contrapositive': 'What do you call ¬Q → ¬P when the original is P → Q?',
  "De Morgan's law": 'Which law changes NOT (P AND Q) into NOT P OR NOT Q?',
  'Algorithm': 'What is a clear, finite set of steps for solving a problem?',
  'Loop tracing': 'What do you call following each loop cycle and recording how values change?',
  'NOT': 'Which logic operator changes true to false and false to true?',
  'Logical equivalence': 'What relationship do two expressions have if their truth tables match?',
  'Tautology': 'What do you call a logical expression that is always true?',
  'Thread': 'What is a path of execution inside a process called?',
  'Context switch': 'What happens when the OS saves one task’s state and loads another?',
  'Preemptive scheduling': 'What scheduling method lets the OS interrupt a running task?',
  'Round Robin': 'Which scheduler gives each ready task a fixed time slice in turn?',
  'Starvation': 'What is it called when a task waits indefinitely while others keep getting resources?',
  'LRU': 'Which page replacement method removes the page whose last access was longest ago?',
  'Frame': 'What is a fixed-size block of physical RAM called?',
  'Pagefile': 'What Windows file can back memory pages on disk?',
  'Page fault': 'What happens when a program needs a page that is not in RAM?',
  'Synchronization': 'What coordinates concurrent tasks so shared data is used safely?',
  'Virtual memory': 'What gives a process its own address space, with disk backing when needed?',
  'Semaphore': 'What counter-based tool limits how many threads can use a resource?',
  'Working set': 'What is the set of memory pages a process used recently?',
  'Functional requirement': 'What type of requirement describes what a system must do?',
  'Non-functional requirement': 'What type of requirement sets a quality target, such as response time?',
  'Verification': 'What checks whether a product follows its specification?',
  'Validation': 'What checks whether a product meets the user’s real need?',
  'Unit testing': 'What testing checks one small function or component by itself?',
  'Integration testing': 'What testing checks whether combined modules work together?',
  'Acceptance testing': 'What testing checks whether users or stakeholders accept the system?',
  'Agile': 'What development approach uses short cycles and regular feedback?',
  'Scrum': 'What Agile framework organizes work into Sprints?',
  'Version control': 'What system tracks file changes and lets collaborators review history?',
  'Waterfall': 'What development model follows phases in a mostly sequential order?',
  'Regression testing': 'What testing checks that a change did not break existing behavior?',
  'Coupling': 'What measures how strongly software modules depend on one another?',
  'Class': 'What OOP blueprint defines the data and behavior of its objects?',
  'Encapsulation': 'What OOP principle groups data with methods and controls access?',
  'Abstraction': 'What OOP principle shows essential behavior while hiding details?',
  'Inheritance': 'What lets a child class reuse or extend a parent class?',
  'Polymorphism': 'What lets the same operation behave differently for different objects?',
  'Method overloading': 'What uses the same method name with different parameter lists?',
  'Method overriding': 'What happens when a child class replaces an inherited method?',
  'Method signature': 'What identifies a method by its name and parameter list?',
  'Constructor': 'What initializes a new object when it is created?',
  'Composition': 'What OOP relationship is a strong whole-part ownership relationship?',
  'Object': 'What is an instance of a class called?',
  'Interface': 'What declares operations that implementing classes must provide?',
  'Dynamic dispatch': 'What chooses an overridden method at runtime based on the object’s type?',
  'TCP': 'Which transport protocol provides reliable, ordered delivery?',
  'TCP segment': 'What is a TCP unit of data called?',
  'Network layer': 'Which OSI layer handles IP addressing and routing?',
  'DNS': 'Which service translates a domain name into an IP address?',
  'ARP': 'Which protocol finds the MAC address for a local IPv4 address?',
  'Router': 'Which device forwards IP packets between networks?',
  'Routing': 'What determines a path for packets through a network?',
  'Flow control': 'What prevents a sender from overwhelming its receiver?',
  'Subnetting': 'How many usable host addresses are in a conventional IPv4 /27 subnet?',
  'Ports': 'What numbers direct TCP or UDP data to the right application on a host?',
  'MAC address': 'What address identifies a network interface on a local link?',
  'Forwarding': 'What is sending one packet out the chosen router interface called?',
  'Congestion control': 'What adjusts sending speed when a network path is overloaded?',
  'Fetch-decode-execute': 'What are the three basic steps of the CPU instruction cycle?',
  'ALU': 'Which CPU part performs arithmetic and logical operations?',
  'Temporal locality': 'What do we call the tendency to reuse recently accessed data?',
  'CIA triad': 'What security model covers confidentiality, integrity, and availability?',
  'Hashing': 'Which process is designed to be one-way?',
  'Salt': 'What random value is added before hashing a password?',
  'Password verification': 'What checks a login password against its stored hash?',
  'Password reset token': 'What short-lived secret is used to authorize a password reset?',
  'Phishing': 'What attack tricks someone into giving up sensitive information?',
  'Least privilege': 'What principle gives users only the access they need?',
  'Confidentiality': 'Which CIA property prevents unauthorized disclosure of information?',
  'Authentication': 'What process verifies who a user is?',
  'Authorization': 'What process checks what a verified user may access?',
  'Primary key': 'What uniquely identifies each row in a database table?',
  'Composite key': 'What key uses two or more columns together?',
  'Foreign key': 'What column refers to a key in another table?',
  '1NF': 'Which normal form requires atomic values in table cells?',
  '2NF': 'Which normal form removes partial dependencies on a composite key?',
  '3NF': 'Which normal form removes transitive dependencies?',
  'INNER JOIN': 'Which SQL join returns only rows that match in both tables?',
  'HAVING': 'Which SQL clause filters grouped results?',
  'Atomicity': 'Which ACID property means a transaction happens completely or not at all?',
  'Index': 'What database structure speeds up lookups on selected columns?',
  'Candidate key': 'What minimal set of columns can uniquely identify a row?',
  'LEFT JOIN': 'Which SQL join keeps every row from the left table?',
  'Isolation': 'Which ACID property keeps concurrent transactions from interfering?',
  'Mean': 'What do you call the arithmetic average of a set of numbers?',
  'Median': 'What is the middle value in a sorted set of numbers?',
  'Mode': 'What is the most frequent value in a data set?',
  'Standard deviation': 'What measures how spread out values are around the mean?',
  'Correlation': 'What term describes an association between variables without proving cause and effect?',
  'Supervised learning': 'What type of learning trains on labeled examples?',
  'Classification': 'What prediction task assigns data to categories?',
  'Regression': 'What prediction task estimates a continuous number?',
  'Overfitting': 'What happens when a model learns training data too closely and performs poorly on new data?',
  'Precision': 'What metric is TP ÷ (TP + FP)?',
  'Clustering': 'What task groups similar data without labels?',
  'Recall': 'What metric is TP ÷ (TP + FN)?',
  'Confusion matrix': 'What table counts true positives, false positives, true negatives, and false negatives?',
  'B2C': 'What business model sells directly from a business to consumers?',
  'B2B': 'What business model sells from one business to another?',
  'HTML': 'What language gives a web page its structure?',
  'CSS': 'What language controls a web page’s visual style?',
  'JavaScript': 'What language commonly adds interactivity to web pages?',
  'CSS specificity': 'What decides which CSS selector wins when rules conflict?',
  'Responsive design': 'What design approach adapts layouts to different screen sizes?',
  'HTTP GET': 'Which HTTP method usually retrieves a resource?',
  'HTTP status codes': 'What three-digit numbers describe an HTTP response result?',
  'HTTPS': 'What secure version of HTTP uses TLS to protect web traffic?',
  'Cookie': 'What small piece of data can a website ask the browser to store?',
  'Session': 'What keeps track of a user across multiple web requests?',
  'CORS': 'What browser mechanism controls permitted requests across origins?'
};

// These prompts accept abbreviations, expanded names, or calculated values.
const clearPromptAnswers = {
  'Byte': ['byte'], 'RAM': ['RAM'],
  'System software': ['system software'], 'Binary to decimal': ['10'],
  'Hexadecimal': ['F'], 'SaaS': ['SaaS', 'software as a service'],
  'Material implication': ['P true Q false', 'P is true and Q is false'],
  'Thread': ['thread'], 'Starvation': ['starvation'],
  'LRU': ['LRU', 'least recently used'],
  'Frame': ['frame'], 'Page fault': ['page fault'],
  'Pagefile': ['pagefile.sys', 'pagefile'],
  'Class': ['class'], 'TCP': ['TCP'],
  'TCP segment': ['segment', 'TCP segment'],
  'Network layer': ['network layer'], 'DNS': ['DNS'],
  'ARP': ['ARP'], 'Router': ['router'],
  'Routing': ['routing'],
  'Flow control': ['flow control'], 'Subnetting': ['30'],
  'ALU': ['ALU'], 'Temporal locality': ['temporal locality'],
  'Hashing': ['hashing'],
  '2NF': ['2NF', 'second normal form'],
  '3NF': ['3NF', 'third normal form'],
  'Correlation': ['correlation'],
  'Overfitting': ['overfitting'],
  'HTTP GET': ['GET'], 'HTTPS': ['HTTPS'],
  'Fetch-decode-execute': ['fetch decode execute', 'fetch, decode, execute']
};

function promptAnswerFor(concept) {
  return (clearPromptAnswers[concept] || [concept])[0];
}

// Keep answer checking flexible, but always teach the correctly capitalized term.
const displayAnswers = {
  'Byte': 'Byte',
  'RAM': 'RAM — Random Access Memory',
  'System software': 'System software',
  'Binary to decimal': '10',
  'Hexadecimal': 'F',
  'SaaS': 'SaaS — Software as a Service',
  'ROM': 'ROM — Read-Only Memory',
  'PaaS': 'PaaS — Platform as a Service',
  'AND': 'AND', 'OR': 'OR', 'XOR': 'XOR — Exclusive OR', 'NOT': 'NOT',
  'Material implication': 'P is true and Q is false',
  'Thread': 'Thread',
  'Starvation': 'Starvation',
  'LRU': 'LRU — Least Recently Used',
  'Frame': 'Frame',
  'Pagefile': 'pagefile.sys',
  'Page fault': 'Page fault',
  'Class': 'Class',
  'TCP': 'TCP — Transmission Control Protocol',
  'TCP segment': 'TCP segment',
  'Network layer': 'Network layer',
  'DNS': 'DNS — Domain Name System',
  'ARP': 'ARP — Address Resolution Protocol',
  'Router': 'Router',
  'Routing': 'Routing',
  'Flow control': 'Flow control',
  'Subnetting': '30 usable host addresses',
  'ALU': 'ALU — Arithmetic Logic Unit',
  'Temporal locality': 'Temporal locality',
  'CIA triad': 'CIA triad — Confidentiality, Integrity, and Availability',
  'Hashing': 'Hashing',
  '2NF': '2NF — Second Normal Form',
  '3NF': '3NF — Third Normal Form',
  'Correlation': 'Correlation',
  'Overfitting': 'Overfitting',
  'B2C': 'B2C — Business-to-Consumer',
  'B2B': 'B2B — Business-to-Business',
  'HTML': 'HTML — HyperText Markup Language',
  'CSS': 'CSS — Cascading Style Sheets',
  'HTTP GET': 'GET',
  'HTTPS': 'HTTPS — Hypertext Transfer Protocol Secure',
  'CORS': 'CORS — Cross-Origin Resource Sharing',
  'Fetch-decode-execute': 'Fetch, decode, and execute'
};

function displayAnswerFor(concept) {
  return displayAnswers[concept] || promptAnswerFor(concept);
}

// Final Round wording stays concise while the thinking demand increases by level.
const clearFinalPrompts = {
  easy: {
    'ROM': 'Which non-volatile memory keeps its contents when power is removed?',
    'NOT': 'Which Boolean operator reverses a truth value?',
    'Virtual memory': 'What gives a process its own virtual address space?',
    'Waterfall': 'Which development model moves through mostly sequential phases?',
    'Object': 'What is an instance of a class called?',
    'MAC address': 'Which address identifies a network interface on a local link?',
    'Confidentiality': 'Which CIA property prevents unauthorized disclosure?',
    'Candidate key': 'What minimal set of columns can uniquely identify a database row?',
    'Clustering': 'Which learning task groups similar examples without labels?',
    'Cookie': 'What small piece of data can a website store in a browser?'
  },
  average: {
    'PaaS': 'A developer deploys an app without managing servers or the operating system. Which cloud model is this?',
    'Logical equivalence': 'Two expressions match on every row of their truth tables. What relationship do they have?',
    'Semaphore': 'Only three workers may use a shared resource at once. Which counter-based tool can enforce this?',
    'Regression testing': 'After a code change, old tests are rerun to find broken behavior. What testing is this?',
    'Interface': 'Several classes promise to provide the same operations. Which OOP construct defines that contract?',
    'Forwarding': 'A router sends one packet through the interface selected by its table. What action is this?',
    'Authentication': 'A user proves their identity with a password or biometric. What process is this?',
    'LEFT JOIN': 'A query must keep every left-table row, even without a match. Which join should it use?',
    'Recall': 'Which classification metric equals TP ÷ (TP + FN)?',
    'Session': 'A site must remember a logged-in user across HTTP requests. What mechanism tracks that state?'
  },
  difficult: {
    "Two's complement": 'An 8-bit value is inverted and then increased by 1 to form its negative. Which representation is being used?',
    'Tautology': 'An expression is true for every possible assignment of its variables. What is it called?',
    'Working set': 'A process repeatedly uses the same group of pages. Which OS term describes this active page set?',
    'Coupling': 'Changing one module forces changes in many others. Which design quality is probably too high?',
    'Dynamic dispatch': 'A base reference calls the child object’s overridden method at runtime. Which mechanism selected it?',
    'Congestion control': 'A sender slows down because the network path is overloaded. Which control mechanism is acting?',
    'Authorization': 'A signed-in user is denied the admin page because of their permissions. Which check failed?',
    'Isolation': 'Concurrent transactions must not expose unsafe intermediate states to one another. Which ACID property applies?',
    'Confusion matrix': 'Which table organizes TP, FP, TN, and FN for a classifier?',
    'CORS': 'A server uses HTTP headers to permit selected cross-origin browser requests. Which mechanism is this?'
  }
};

function finalPromptFor(level, question) {
  return clearFinalPrompts[level]?.[question.concept] || question.prompt;
}

const clearFinalAnswers = {
  'Object': ['object']
};

function finalAnswersFor(question) {
  return clearFinalAnswers[question.concept] || question.answers;
}

// Reference libraries used to validate the wording for each subject area.
const trustedReferences = {
  'Basic Computer Concepts / General IT': {label:'AWS: Cloud service models',url:'https://aws.amazon.com/types-of-cloud-computing/'},
  'Logic Formulation': {label:'OpenStax: Equivalent statements',url:'https://openstax.org/books/contemporary-mathematics/pages/2-5-equivalent-statements'},
  'Operating Systems': {label:'Microsoft Learn: Virtual memory and working sets',url:'https://learn.microsoft.com/en-us/windows/win32/procthread/process-working-set'},
  'Software Engineering': {label:'The official Scrum Guide',url:'https://scrumguides.org/scrum-guide.html'},
  'Object-Oriented Programming': {label:'Microsoft Learn: Object-oriented programming',url:'https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/object-oriented/'},
  'Computer Networks and Telecommunication': {label:'IETF RFC 9293: TCP',url:'https://www.rfc-editor.org/rfc/rfc9293.html'},
  'Computer Architecture and IT Security': {label:'NIST Cybersecurity Glossary',url:'https://csrc.nist.gov/glossary'},
  'Database Management System': {label:'PostgreSQL documentation',url:'https://www.postgresql.org/docs/current/tutorial.html'},
  'Data Science and Analytics': {label:'scikit-learn metrics documentation',url:'https://scikit-learn.org/stable/api/sklearn.metrics.html'},
  'E-commerce and Web Design': {label:'MDN Web Docs',url:'https://developer.mozilla.org/en-US/docs/Web'}
};

function trustedReferenceFor(category) {
  return trustedReferences[category] || null;
}

// Wording for the original multiple-choice set. Choices and explanations stay
// attached to their existing source concept.
const clearBasePrompts = {
  'Firmware': 'What is the low-level software that helps control a device?',
  'Compiler': 'What translates source code before the translated program runs?',
  'Interpreter': 'What runs source instructions through a runtime?',
  'Virtualization': 'What lets one physical computer run multiple virtual machines?',
  'SaaS': 'Which cloud model gives users a complete app, like webmail?',
  'Thread': 'What is a thread?',
  'Context switch': 'What does the OS do during a context switch?',
  'Preemptive scheduling': 'What can the OS do with a running task in preemptive scheduling?',
  'Round Robin': 'Which scheduler gives each task a fixed time slice?',
  'Starvation': 'What is starvation in process scheduling?',
  'LRU': 'Which page does LRU choose for replacement?',
  'Frame': 'What is a frame in memory management?',
  'Pagefile': 'What does the Windows pagefile do?',
  'Page fault': 'What is a page fault?',
  'Synchronization': 'What lets only one thread enter a critical section at a time?',
  'Verification': 'What question does verification answer?',
  'Validation': 'What question does validation answer?',
  'Unit testing': 'What testing checks one small component by itself?',
  'Integration testing': 'What testing checks whether modules work together?',
  'Acceptance testing': 'What testing checks if a system meets user needs?',
  'Method signature': 'Which parts identify a method signature?',
  'TCP': 'What delivery service does TCP provide?',
  'TCP segment': 'What is a TCP segment?',
  'Network layer': 'What does the network layer handle?',
  'DNS': 'What does DNS do?',
  'ARP': 'What does ARP do?',
  'Router': 'What does a router do?',
  'Routing': 'What does routing determine?',
  'Flow control': 'What does flow control prevent?',
  'Ports': 'Why do TCP and UDP use port numbers?',
  'ALU': 'What does the ALU do?',
  'Temporal locality': 'What does temporal locality mean?',
  'Hashing': 'What is hashing used for?',
  'Password verification': 'How should a system check a salted, hashed password?',
  'Password reset token': 'Why should a password-reset link expire after use?',
  'Least privilege': 'How much access should least privilege give a user?',
  '2NF': 'What problem stops a table with a composite key from reaching 2NF?',
  '3NF': 'What do you call a non-key column depending on another non-key column?',
  'Correlation': 'What does correlation describe?',
  'Overfitting': 'What is overfitting?',
  'HTTP GET': 'What is HTTP GET generally used for?'
};
